server:
  port: 9195
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanessaandrandrin@gmail.com
    password: xeswbvtvdbpxkelr
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: prod
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=warehouse_management;encrypt=true;trustServerCertificate=true
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Warehouse Manager Application
    description: This is the monitoring dashboard to trace the activities of all requests and responses
    version: 1.0.0